version: '3.8'

services:
  pdf_converter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/input
      - ./output:/output

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
